name: CI

on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install pipenv
        run: pip install --user pipenv
      - name: Use pipfile
        run: python -m pipenv install --system
      - name: Testing
        run: python -m unittest discover tests  -bv
