name: CI

on:
  [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v2
      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Testing
        run: python -m unittest discover tests  -bv

  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://github/super-linter:v2.1.0